services: 
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ExamGeneratorData:/ExamGenerator/Persistence/data
  
volumes: 
   ExamGeneratorData: